### ISSUE TITLE
Saving layout for any folder

### ISSUE THREAD

**Issue by JJRousseau** [TomONeill/persistentdesktopicons#1]
Any chance you could expand this to save icon layouts for any arbitrary folder? I use the root of my E drive as my desktop and would love to be able to save the icon layout just as for the desktop.

**Comment by TomONeill** [comment]
I have never seen somebody make use of a drive as a desktop. Interesting!
It is not in my priority to make such a thing happen, though I would think the application should be able to handle that already (but I guess not, otherwise there would not be an open issue here).

I have not updated the project in a year, mainly because I do not have this issue myself anymore (kind of selfish, I know :(, but it's a lot harder to test the application than it already was)
