### ISSUE TITLE
Directories bug

### ISSUE THREAD

**Issue by ghost** [TomONeill/persistentdesktopicons#3]
I don't know what is the reason.
But, when you're dragging folder into trash can instead of deleting it in other ways, the icon of itself stands still.

**Comment by TomONeill** [comment]
Do you mean that after dragging it onto the trash bin icon it doesn't get removed from the desktop?
Is the dictory in the bin after doing so?
What happens when you empty the bin?
What happens when you try to move the directory to any other place on the desktop?

Obviously this shouldn't happen. The application should only do something when it detects resolution changes. Not when dragging icons, however I have been thinking about that approach, but can't remember if I ever implemented it into one of the older versions. I don't think I did.

**Comment by TomONeill** [comment]
I am closing this one due to inactivity.
